// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mieszkaniec.Model.Context;

#nullable disable

namespace Mieszkaniec.Migrations
{
    [DbContext(typeof(MieszkaniecDbContext))]
    [Migration("20260811073723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mieszkaniec.Model.Entities.AneksUmowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataZawarcia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NowaDataDo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("NowaStawkaCzynszu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumerAneksu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpisZmian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UmowaNajmuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UmowaNajmuId");

                    b.ToTable("AneksyUmow");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.KosztorysMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaJednostkowa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ilosc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NazwaMaterialu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PraceRemontoweId")
                        .HasColumnType("int");

                    b.Property<decimal>("WartoscCalkowita")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PraceRemontoweId");

                    b.ToTable("KosztorysMaterial");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.LokalWynajem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZaM2")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("NajemcaId")
                        .HasColumnType("int");

                    b.Property<string>("NumerLokalu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObiektId")
                        .HasColumnType("int");

                    b.Property<decimal>("PowierzchniaM2")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SvgElementId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypLokalu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NajemcaId");

                    b.HasIndex("ObiektId");

                    b.ToTable("LokaleWynajem");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Najemca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("CzyArchiwalny")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataArchiwizacji")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NazwaFirmyOsoby")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nip")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("OsobaKontaktowa")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("REGON")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Najemcy");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Obiekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("CzyArchiwum")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Kubatura")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("LiczbaKondygnacji")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumerEwidencyjny")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PowUzytkowa")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RokBudowy")
                        .HasColumnType("int");

                    b.Property<string>("Wyposazenie")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Wysokosc")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("obiekty");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.PraceRemontowe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRozpoczeciaFaktyczna")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRozpoczeciaPlanowana")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataZakonczeniaFaktyczna")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataZakonczeniaPlanowana")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataZgloszeniaUsterki")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GodzinyDziennie")
                        .HasColumnType("int");

                    b.Property<decimal>("KosztCalkowityRobocizny")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KosztFaktyczny")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KosztSzacowany")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiczbaPracownikow")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ObiektId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("OsobaZglaszajaca")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PriorytetUsterkiId")
                        .HasColumnType("int");

                    b.Property<decimal>("RobociznaStawkaGodzinowa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RodzajUsterkiId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SzacowanaLiczbaDni")
                        .HasColumnType("int");

                    b.Property<int?>("UsterkaId")
                        .HasColumnType("int");

                    b.Property<string>("WykonawcaNazwa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ObiektId");

                    b.HasIndex("PriorytetUsterkiId");

                    b.HasIndex("RodzajUsterkiId");

                    b.ToTable("PraceRemontowe");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.PriorytetUsterki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodKoloru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("MaksCzasReakcjiGodziny")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Poziom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriorytetyUsterek");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Przeglad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNastepnego")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataWykonania")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObiektId")
                        .HasColumnType("int");

                    b.Property<string>("OsobaWykonujaca")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerminDefinicjaId")
                        .HasColumnType("int");

                    b.Property<string>("WynikOcena")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ObiektId");

                    b.HasIndex("TerminDefinicjaId");

                    b.ToTable("przeglady");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.RodzajUsterki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyWymagaUprawnien")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KlasaIkony")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RodzajeUsterek");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.TerminDefinicja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CzestoscMiesiace")
                        .HasColumnType("int");

                    b.Property<int>("DniPowiadomienia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaTypu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("terminy_definicje");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.UmowaLokal", b =>
                {
                    b.Property<int>("UmowaNajmuId")
                        .HasColumnType("int");

                    b.Property<int>("LokalWynajemId")
                        .HasColumnType("int");

                    b.Property<bool>("CzyRyczalt")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("WynegocjowanaCenaZaM2")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("UmowaNajmuId", "LokalWynajemId");

                    b.HasIndex("LokalWynajemId");

                    b.ToTable("UmowaLokal");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Uprawnienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaSystemowa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Uprawnienia");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.UsterkiBud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyArchiwum")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataZakonczeniaNaprawy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataZgloszenia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObiektId")
                        .HasColumnType("int");

                    b.Property<string>("OpisZgłoszenia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OsobaZglaszajaca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PriorytetUsterkiId")
                        .HasColumnType("int");

                    b.Property<int>("RodzajUsterkiId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UwagiKonserwatora")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ObiektId");

                    b.HasIndex("PriorytetUsterkiId");

                    b.HasIndex("RodzajUsterkiId");

                    b.ToTable("UsterkiBud");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Zalacznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NazwaPliku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PrzegladId")
                        .HasColumnType("int");

                    b.Property<int>("RozmiarKB")
                        .HasColumnType("int");

                    b.Property<string>("SciezkaMagazyn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UsterkiBudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrzegladId");

                    b.HasIndex("UsterkiBudId");

                    b.ToTable("zalaczniki");
                });

            modelBuilder.Entity("RolaUzytkownik", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownicyId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UzytkownicyId");

                    b.HasIndex("UzytkownicyId");

                    b.ToTable("UzytkownikRola", (string)null);
                });

            modelBuilder.Entity("UmowaNajmu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywna")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataDo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataOd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NajemcaId")
                        .HasColumnType("int");

                    b.Property<string>("NumerUmowy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NajemcaId");

                    b.ToTable("UmowyNajmu");
                });

            modelBuilder.Entity("UprawnienieUzytkownik", b =>
                {
                    b.Property<int>("UprawnieniaId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownicyId")
                        .HasColumnType("int");

                    b.HasKey("UprawnieniaId", "UzytkownicyId");

                    b.HasIndex("UzytkownicyId");

                    b.ToTable("UzytkownikUprawnienie", (string)null);
                });

            modelBuilder.Entity("ZalacznikUmowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NazwaPliku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SciezkaPliku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UmowaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UmowaId");

                    b.ToTable("ZalacznikiUmow");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.AneksUmowy", b =>
                {
                    b.HasOne("UmowaNajmu", "UmowaNajmu")
                        .WithMany("Aneksy")
                        .HasForeignKey("UmowaNajmuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UmowaNajmu");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.KosztorysMaterial", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.PraceRemontowe", "PraceRemontowe")
                        .WithMany("Materialy")
                        .HasForeignKey("PraceRemontoweId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PraceRemontowe");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.LokalWynajem", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Najemca", "Najemca")
                        .WithMany("WynajmowaneLokale")
                        .HasForeignKey("NajemcaId");

                    b.HasOne("Mieszkaniec.Model.Entities.Obiekt", "Obiekt")
                        .WithMany("Lokale")
                        .HasForeignKey("ObiektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Najemca");

                    b.Navigation("Obiekt");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.PraceRemontowe", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Obiekt", "Obiekt")
                        .WithMany()
                        .HasForeignKey("ObiektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.PriorytetUsterki", "PriorytetUsterki")
                        .WithMany()
                        .HasForeignKey("PriorytetUsterkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.RodzajUsterki", "RodzajUsterki")
                        .WithMany()
                        .HasForeignKey("RodzajUsterkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obiekt");

                    b.Navigation("PriorytetUsterki");

                    b.Navigation("RodzajUsterki");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Przeglad", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Obiekt", "Obiekt")
                        .WithMany("Przeglady")
                        .HasForeignKey("ObiektId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.TerminDefinicja", "TerminDefinicja")
                        .WithMany()
                        .HasForeignKey("TerminDefinicjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obiekt");

                    b.Navigation("TerminDefinicja");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.UmowaLokal", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.LokalWynajem", "LokalWynajem")
                        .WithMany("HistoriaUmow")
                        .HasForeignKey("LokalWynajemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmowaNajmu", "UmowaNajmu")
                        .WithMany("WynajmowaneLokale")
                        .HasForeignKey("UmowaNajmuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LokalWynajem");

                    b.Navigation("UmowaNajmu");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.UsterkiBud", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Obiekt", "Obiekt")
                        .WithMany()
                        .HasForeignKey("ObiektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.PriorytetUsterki", "PriorytetUsterki")
                        .WithMany()
                        .HasForeignKey("PriorytetUsterkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.RodzajUsterki", "RodzajUsterki")
                        .WithMany()
                        .HasForeignKey("RodzajUsterkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obiekt");

                    b.Navigation("PriorytetUsterki");

                    b.Navigation("RodzajUsterki");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Zalacznik", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Przeglad", "Przeglad")
                        .WithMany("Zalaczniki")
                        .HasForeignKey("PrzegladId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mieszkaniec.Model.Entities.UsterkiBud", "UsterkiBud")
                        .WithMany("Zalaczniki")
                        .HasForeignKey("UsterkiBudId");

                    b.Navigation("Przeglad");

                    b.Navigation("UsterkiBud");
                });

            modelBuilder.Entity("RolaUzytkownik", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Rola", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UzytkownicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UmowaNajmu", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Najemca", "Najemca")
                        .WithMany()
                        .HasForeignKey("NajemcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Najemca");
                });

            modelBuilder.Entity("UprawnienieUzytkownik", b =>
                {
                    b.HasOne("Mieszkaniec.Model.Entities.Uprawnienie", null)
                        .WithMany()
                        .HasForeignKey("UprawnieniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mieszkaniec.Model.Entities.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UzytkownicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZalacznikUmowy", b =>
                {
                    b.HasOne("UmowaNajmu", "UmowaNajmu")
                        .WithMany("Zalaczniki")
                        .HasForeignKey("UmowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UmowaNajmu");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.LokalWynajem", b =>
                {
                    b.Navigation("HistoriaUmow");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Najemca", b =>
                {
                    b.Navigation("WynajmowaneLokale");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Obiekt", b =>
                {
                    b.Navigation("Lokale");

                    b.Navigation("Przeglady");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.PraceRemontowe", b =>
                {
                    b.Navigation("Materialy");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.Przeglad", b =>
                {
                    b.Navigation("Zalaczniki");
                });

            modelBuilder.Entity("Mieszkaniec.Model.Entities.UsterkiBud", b =>
                {
                    b.Navigation("Zalaczniki");
                });

            modelBuilder.Entity("UmowaNajmu", b =>
                {
                    b.Navigation("Aneksy");

                    b.Navigation("WynajmowaneLokale");

                    b.Navigation("Zalaczniki");
                });
#pragma warning restore 612, 618
        }
    }
}
