<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);BenchmarkSuite1/**;publish/**</DefaultItemExcludes>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Shared\uploads\288f1bab-4309-4f17-873e-8a37d9302843_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\38f9b6a4-04aa-49bf-a6a9-96bd8fc4d118_zarzadzenie_wgk.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\47cc5656-3e07-431c-9739-6380d06384dd_zarzadzenie_wgk.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\5b158e3c-71c7-4b13-b106-af99813cba11_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\9fcfadec-cd05-4023-b815-37055d2eeccb_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\c31fec6e-0818-47cc-99d8-1710a51df86c_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\f5bec8e4-72de-4e40-8830-96769885805e_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Shared\uploads\fc75bd3b-d6e8-4516-b5cb-f09acfd104c1_nabor_BKP_20022026.pdf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Shared\upload_umowy\" />
    <Folder Include="wwwroot\uploads1111\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="BootstrapBlazor" Version="10.6.0" />
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="9.5.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
